### ISSUE TITLE
Improve auth startup time

### ISSUE THREAD

**Issue by giovannicuriel** [dojot/auth#86]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request
 

* **Do you want to request a *feature* or report a *bug*?**
Bug
PS: I think we might want to remove this question. It is already answered when setting the first checkbox options.

* **What is the current behavior?**
Auth takes too much time to start up. It compiles the bad password list from `password.txt` file before it can send responses for tenant list requests. Therefore, all services that need this list (almost all services) will keep rebooting until everything in Auth it up and running.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Just start the thing and grab a cup of coffee.

* **What is the expected behavior?**
As this procedure is indeed heavy on CPU resources, it could be moved to a separate thread (blocking just user creation and password reset features). Thus it could respond for other requests much quicker, and substantially decrease the amount of time for services to become usable.

* **What is the motivation / use case for changing the behavior?**
User happiness.

* **Please tell us about your environment:**
  
  - Version: 0.2.x
  - Environment: [kubernetes, docker-compose, standalone]
  - Operating system: [Ubuntu 16.04, Fedora 28, Ubuntu on VirtualBox (Windows 10), etc.]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by bizetti** [comment]
Ticket analysis meeting (April, 17th): Priority low.

**Comment by bizetti** [comment]
Component will be deprecated. Ticket will not be fixed.
